[project]
name = "ktmb-scraper"
version = "0.1.0"
description = ""
readme = "README.md"
dependencies = [
    "click>=8.0.0",
    "loguru>=0.7.0",
    "playwright>=1.40.0",
    "pydantic>=2.0.0",
    "python-dateutil>=2.8.0",
    "requests>=2.25.0",
    "python-dotenv>=1.0.0",
]
